apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME-0-production-testing
  namespace: chain-prd-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME-0-production-testing
  template:
    metadata:
      labels:
        app: $APP_NAME-0-production-testing
    spec:
      containers:
      - name: $APP_NAME-0-production-testing
        command: [ "/bin/sh","-c","
                  sequencerd start  --json-rpc.address 0.0.0.0:8545 --json-rpc.api eth,txpool,personal,net,debug,web3,miner --api.enable true --minimum-gas-prices 0.0001aseq  --home /data/blocks/zkevm/sequencer/zkevm-sequencer-0" ]
        args: [ ""]
        image:  $REGISTRY/$APP_NAME:SNAPSHOT-$BUILD_NUMBER
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 2
            memory: 4Gi
        volumeMounts:
          - name: data
            mountPath: /data/blocks
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 1317
          - containerPort: 8545
          - containerPort: 26657
          - containerPort: 26656
        env:
          - name: TZ
            value: GMT
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
      - name: data
        persistentVolumeClaim:
          claimName: vmchain-ssd-pvc-0
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - $APP_NAME-0-production-testing
              topologyKey: "kubernetes.io/hostname"
#  volumeClaimTemplates:
#    - metadata:
#        name: data
#      spec:
#        accessModes: [ "ReadWriteMany" ]
#        storageClassName: "mvmchain-local-storage"
#        resources:
#          requests:
#            storage: 10Gi